ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDTDCCAjSgAwIBAgIRAOHKwBPrlIfqOj06AG4ocykwDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI0MDkyNTEwMzYxMFoXDTM0
  MDkyMzEwMzYxMFowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
  hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw+LIJ/lxxPcb4RWZVfkYioAnClQv+K1U
  ftWEGn7hiAFiuqf9QdYltlijkRckvAgmwr/FF4/uet6lM8QWM1JmCfUP3GxbiKMS
  njLdcuklQwNqpeNXFgj0aV+xfzjDFaJQWBBzB1Y2pfFPDtkdjnUuoqyxpN7lsm8C
  s59wexo9rPUEalWIKQqutuk+P4O21qOzT67fP+C4bNQYS+4dRMia7BPuwEyRUGSy
  I3esyPm+54y9sOfS/BZBfd7pjQY7r3wB5Bvm8uOqpdW4t60NSE0kM2VEaUMwWP0p
  fSmaY6IVPhKsDRa0uURqmzdQX66WPdFn6LGIgEY6LY/1gXvXCAyocwIDAQABo4GM
  MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
  AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUZlVuSkXJ6hjpwYf+r9UnSvzw
  JeMwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
  KoZIhvcNAQELBQADggEBAEWeUDoXi2XHHh6sskqmx1K5oNNtKzXJRsrykw20kgWT
  NvXzTn7xiWeSFLo8hWUaZtIzm7M56PZVOiLARzuki2ZSThEzUgA2EXJ7nFwfAJ5e
  Bh+ggu6HehdpHiJZREyExOWuiXZJ2V/JlzH/zP880cOATyS56TX5VEOggn4l624g
  7EhwuFKqEnyRu/3wwZl0rW5KY+iJJWkDFp7DzmbV1sIyG7Dz706Xt7Wjh6XC6vqh
  0g6M9b5TuWJxQ85Sg8WukgiunN9X3twPxlfI3HukGNnnWSEW9JEgMhS6olFZcvbU
  zo7ShqyMRPy9D0HrAzGPavrCoTPXYMmIAKxikruQh00=
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDPzCCAiegAwIBAgIQT1IjMaeIC/ejSVuFCUiKKDANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQxMDAxMDk1OTU0WhcNMjUx
  MDAxMDk1OTU0WjAoMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxDzANBgNVBAMTBkxp
  c0RlbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKrgXnoB4Sv47WRa
  dgTe2Co+kVMiQHAdtdYKhmBDiOWdU/QoQJPwftqM7W+ZMoXinZ3E0PDedEajvfZs
  rIUIDNVU0kGq0sByADUNNY+W9ebKm2wnkENIt8wUMYrNZIOPf5XJzXyovdziL6kY
  bBIZBvCLPM97osefNFvoxKmFYOg9HEeSLfPiAGH7rR4zJ4wzV2rzkdTItXi+Rmkw
  4N1BSL7I19z4iNNaB5eatcCvo3wkAaNz5F/9D+p6+HQVc7BI7m2aO0/TLoIXUG2K
  f+uApI9vYmvGKxEC7MYzZQMCP7LvCykSDoOWQsHAFoZGAcRLgLLtpMHcUuaIX4cH
  01N5MrECAwEAAaNzMHEwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUF
  BwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFGZVbkpFyeoY
  6cGH/q/VJ0r88CXjMBEGA1UdEQQKMAiCBkxpc0RlbTANBgkqhkiG9w0BAQsFAAOC
  AQEAMBwq5Me036FS/+YrlTh6PY+Vy7Bl5lviYRM3DRZYs1TjFNFb4xMyKZW+HIw2
  j19coNBasJ9zbvAlzfK3VPfQryzlZqU/WcS7HjYkGwBkIvZ4TXB92agXYC7j/Vgg
  oJYWXGCUnFgzrPz1X2QVl9zxPul70yXCJUeG7t2sOAhszn7iCa28KDy4tIvmjNtN
  L9bOzCvl9VvDLwj7XTrXS9nEjqlSkrGgBW53SWkDfUqSvlg+Pn7ybd9cfTQElBH4
  P36lULe2/FmFNWUb/MqluU+Fl7BNa5/k8rPhZByBs3Ujh0Nmj/WKfj02vL3cIwia
  OzyF1plm0cP10nz1/NYRl9H08A==
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEogIBAAKCAQEAquBeegHhK/jtZFp2BN7YKj6RUyJAcB211gqGYEOI5Z1T9ChA
  k/B+2oztb5kyheKdncTQ8N50RqO99myshQgM1VTSQarSwHIANQ01j5b15sqbbCeQ
  Q0i3zBQxis1kg49/lcnNfKi93OIvqRhsEhkG8Is8z3uix580W+jEqYVg6D0cR5It
  8+IAYfutHjMnjDNXavOR1Mi1eL5GaTDg3UFIvsjX3PiI01oHl5q1wK+jfCQBo3Pk
  X/0P6nr4dBVzsEjubZo7T9MughdQbYp/64Ckj29ia8YrEQLsxjNlAwI/su8LKRIO
  g5ZCwcAWhkYBxEuAsu2kwdxS5ohfhwfTU3kysQIDAQABAoIBAGprB4u2hfRrt/SK
  vft0iW1tv/XlW/o3FpqxvVRQWv6dR77EHsvDuE0F/Y1F/IgTRRQPkgygjgu8SD8j
  GSJUjCGEDNnmuBAwL17a1iOR4Z0VS0xFK3wr2oOXg+8s0U952/x+TKI5ON1KZGJM
  Gmn++ipunLWfCxaFWQdwZKIqtdqLx9xbf3Zlp0YtHlFRtJruM3NL1k82iFp3NvkD
  vcNbo/OPBf3ZWBSjb2C4YXqY1OmzTOD9Ai+XqC5n5yib7o+JG5XZ3yLcU9hJyn/T
  R+02jdmI2xgP8EJ4dyF/4nQYumoBE43/qdfARlj+sWaooAl9xL1ZovJTn8OyhaY8
  aZT4pgECgYEA2CN6bAFK77dIfq9KmGXshkJ38UZF6ys3KfgQdg+KF/ErMw6ZqRdl
  XDEJqVZM948xH7PTzP6J86KOdH0ExLIBvBVgKMwMvTxqYzclBalu/lpS0T82xJqy
  42QQmOSM/+PfGq5PqgFd5n5j+zyxjOnf/GPGzdyczNVEBpEiVmRzmxECgYEAymPv
  cOYbkUXsBfS5y0opP1nzMlj0G0of6wWSmqQcCho5gse9IHalCACjdmJ0lovsNinl
  FAVxlNt+6vBdquNo+l2Pxpqb/nl0byf4wboMApiyfNV1Nja7qFpCCIBo7WzUiCWw
  JdPz15xP2sAhc4Q46UdD4/K8bx8oellXgvV33aECgYBx3z9AZ+3zHb00AWZrpEdY
  9Ov8UenEXKBTnD4P9V/r/UOlQqvySkE8sRlF/hHO28Il0bhk6DYGBj7HYJaCisYf
  MaPX2qlbidkDLKp0sS+pEi1P0N4p9tcItk+IPeGLb6K7i9qs1suCBFToqLFibFV1
  w5uaGgECadnNG+nbWlEOAQKBgHBAn2Qx7GZVrsPa6VWsa1Y80JtDJRkhsrRKofZt
  QTQFOZKkr+waggv/NqqJjvqU3s1nzSuenVGfsDQkXv9SJD6AuCbCR/ULbh3cwKbK
  RrEF+jEsv1bzYn/Ml8VZW1kcPIDKznkcpqkWhF/iomsMkfgo06nRTtwfHvdFKDl1
  ZichAoGAbyUgS+ZaS9JeBmHDsOEw+4OLj4o1TlvlMrCax6ACr2b3/hAanf/epJlD
  2dbeAmNL7990O1rYd4g89cvMxts9MWSmo84eKOQimv7j7HYpFs8gA1KYTPA0XLnB
  62MwviHkQ20M7QO+qabTz4KvxnJF+/tEG+WGTM7q7zG1peEZFj0=
  -----END RSA PRIVATE KEY-----
api_connection_string: 10.145.213.127:8001
name: LisDem
