ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDTDCCAjSgAwIBAgIRAOHKwBPrlIfqOj06AG4ocykwDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI0MDkyNTEwMzYxMFoXDTM0
  MDkyMzEwMzYxMFowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
  hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw+LIJ/lxxPcb4RWZVfkYioAnClQv+K1U
  ftWEGn7hiAFiuqf9QdYltlijkRckvAgmwr/FF4/uet6lM8QWM1JmCfUP3GxbiKMS
  njLdcuklQwNqpeNXFgj0aV+xfzjDFaJQWBBzB1Y2pfFPDtkdjnUuoqyxpN7lsm8C
  s59wexo9rPUEalWIKQqutuk+P4O21qOzT67fP+C4bNQYS+4dRMia7BPuwEyRUGSy
  I3esyPm+54y9sOfS/BZBfd7pjQY7r3wB5Bvm8uOqpdW4t60NSE0kM2VEaUMwWP0p
  fSmaY6IVPhKsDRa0uURqmzdQX66WPdFn6LGIgEY6LY/1gXvXCAyocwIDAQABo4GM
  MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
  AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUZlVuSkXJ6hjpwYf+r9UnSvzw
  JeMwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
  KoZIhvcNAQELBQADggEBAEWeUDoXi2XHHh6sskqmx1K5oNNtKzXJRsrykw20kgWT
  NvXzTn7xiWeSFLo8hWUaZtIzm7M56PZVOiLARzuki2ZSThEzUgA2EXJ7nFwfAJ5e
  Bh+ggu6HehdpHiJZREyExOWuiXZJ2V/JlzH/zP880cOATyS56TX5VEOggn4l624g
  7EhwuFKqEnyRu/3wwZl0rW5KY+iJJWkDFp7DzmbV1sIyG7Dz706Xt7Wjh6XC6vqh
  0g6M9b5TuWJxQ85Sg8WukgiunN9X3twPxlfI3HukGNnnWSEW9JEgMhS6olFZcvbU
  zo7ShqyMRPy9D0HrAzGPavrCoTPXYMmIAKxikruQh00=
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDRjCCAi6gAwIBAgIRAP8uqcP1it5K0DoOeenOJ6UwDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI0MTAwMjExMTIyNFoXDTI1
  MTAwMjExMTIyNFowKzEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRIwEAYDVQQDEwlL
  ZXlKYWNrZWkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC5aRY/VWNL
  7n9XsvOpzYKSDAwIbp7sdQ0L8D6EhEG1EkkH+Qp+mikiNrgssG8HZJ/HQZTS52RO
  AlH0Em4jewZX+fas1r0V3enkmWziQINWelohCjnkkoqgKjUmjWR3jZ5F8qcqnOSk
  Gla89GdNz4+uMhXAeTLQ8YaJ/HZRqHffpZwE11JSwIV90KcSku1zHj/nglbFQSaY
  bnMHQuy/QU1tvDrqpCB/WPnxeTsYWOWuxug1vySwqI+8bHzvKrH0Gp67BDqshLfI
  69a3QCtFIqgOevGi6KKFv3sKo7JrcrXTXeNO4hWXf7RCDpGyR3/jZRCrUYUkepZa
  yK8LoUyXCqMrAgMBAAGjdjB0MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggr
  BgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBRmVW5K
  RcnqGOnBh/6v1SdK/PAl4zAUBgNVHREEDTALgglLZXlKYWNrZWkwDQYJKoZIhvcN
  AQELBQADggEBAEJe4/zhbf7OzraQBD6hCVr+KMFaahs/cnSD4jDwUZxddeCYZsTo
  ewHeCaP9UMTXy8lLb1rYPdxF2c1BqmWesUXMH/081VASh/LH3Kd0AxbfhLz47xEC
  4a1/b7SIm0moZGpcmJFFU5S0tbsDuJ8RTyAePCRCS+JrwiJpiAJDFHAgTqVV9XxW
  v/+B7QRgks0g3VBMGCFWnsIQTqEh4eMhenldRydPCzAKacS1dmhVDTfQ0R48JEq+
  UP9ep/Aj6BDUxCRA1uyLlEGe6zO5Z8UTXDAKptNnelE3zA92xcDs7469bgsMAVJ5
  xyYt2lV0z5YCp2oenPkPN57bKpYe9BZ9SlI=
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAuWkWP1VjS+5/V7Lzqc2CkgwMCG6e7HUNC/A+hIRBtRJJB/kK
  fpopIja4LLBvB2Sfx0GU0udkTgJR9BJuI3sGV/n2rNa9Fd3p5Jls4kCDVnpaIQo5
  5JKKoCo1Jo1kd42eRfKnKpzkpBpWvPRnTc+PrjIVwHky0PGGifx2Uah336WcBNdS
  UsCFfdCnEpLtcx4/54JWxUEmmG5zB0Lsv0FNbbw66qQgf1j58Xk7GFjlrsboNb8k
  sKiPvGx87yqx9BqeuwQ6rIS3yOvWt0ArRSKoDnrxouiihb97CqOya3K1013jTuIV
  l3+0Qg6Rskd/42UQq1GFJHqWWsivC6FMlwqjKwIDAQABAoIBAEVXVeityIsXUSy9
  Un+IynJQaxekN297fzudx+PLir9rbUC8FP6wLP4MtOiRu5RqP49HqZ8Oxuad24SK
  eAJw+jhg1a5iSSkqa1UBREWBlxz6eUauCmS/oXSxFFusuYw0vKKwU3COaLwu1Y2p
  YhEptTSSqqvnJ+gYzBZDAwUbGmnbZH7ET9YFtNROoh7ROyTWNPYWanHgKmkz2G0n
  OBTdYezTHWySUbpjgsxsWDWc1Ea8Qgc89C2Q+CCNIEvjzae0m67WU0j1FcWWS/IC
  F/7osKJ/sQMcaQK/cBsMCqyjp8ojrm6gkk1HS4fss5FVGUsfLqzv6Bvw/gTweERg
  FxkGzyECgYEA65fDTKr+J+kcuWGD+bjOch9//tKC2u8fv/lufaKkaj70loPc6VlX
  HK7yB7XQbDGe/yMr3TGdj2EcY8X/cEFeP3yOZuqgMWOVlEYFOZqttszVCr9xHO5/
  /m3da4BbJpSxJo2jVHciA7y2m6pLcxgYFLLiuOVpnIWasunht3TuLYMCgYEAyXiJ
  v6a9jVV/PamA0h2whiX58MBaBfW9OrMW/unrdxlAvFK6HVe2EKYIj/ehiwUJPJ1a
  vNkAdJcrPY97/8FgZvqXJQD+6+6vK3tMba0KORqKJRwaqsMMZzdwNykb+88xgSzL
  WfnZnjrZdb+zPmd8bSCTgrI9OFsDW5vNNT00qzkCgYAq+6xpL4VhWLmh5PXEOQCJ
  d8/NeTDgquIbD3ImP+dJbyUG1RYYCPHIzO5hk71sD/2XRR56o9PAVhJs7bH2FCcS
  5DHC+ymw+R9QRxoq8VqiUGrKJDWJ9sWpcPgF5gw7VMOhahQTlAzDq8mRSxeq7wlt
  tVmCLHEBWqrn254P76iI6wKBgQCPmlxM/9OSPwOf9wa8Pa9KHx2FLgW8w8jqYyab
  8i4EyTosQacpLRC30zC9NVuu1Jsd2mcHvoElmW6XxYMz7CkDndBH7urFTm8LRipW
  7oUf6LvY8axMVRStKYXRu3qXxLpbgYs8ietEblv8IvTnISo+On8KJHOgjLbbADWH
  oiW9eQKBgDHvsA+nIpoCJVm9Uq9+xUYcXkXCQXfMEdDNwQGb2HkR76ZBRex7CjDo
  N+hy5fgMkXmmIOLjLhL1Qu5qGWiUBSsACrQuQAg0dInf1qBNxTwXQ1pWjFSkM2oC
  Pdnsao6zoouq5A9SmStGLe+oLaJSal0oHuH4hVKQEg9AtUuOUV4e
  -----END RSA PRIVATE KEY-----
api_connection_string: 10.145.213.127:8001
name: KeyJackei
