ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDTDCCAjSgAwIBAgIRAIW+yDWgRav+9VbQduAkm2owDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI0MTAyOTEwNDU1OVoXDTM0
  MTAyNzEwNDU1OVowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
  hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArUOcoWx0UQVu3FltLj43R7vdLifhQBB1
  RYmnTPPKiAbApFkLqQB8hZy6RIu7Mu4lKQdocuLjQ1pDEC8zz/VUoYZZWeMV4jCJ
  Szhe60bXjP6pSP95FujL0thwU1FQVH7AtPaE9f6syf3fT/I9vCgpDv5PtFlUC1eY
  U6EHxjdCI/850zkY1DyrpcKe5k850zE/gkUtQxOwII/9XvqYP/zuUUV5Uvcw5OeR
  MtEmg7i/YnIk2vDcBRMd8Ijys8k7JZ1yqBaLnkzbETty975nyjBQ6i/m9BlfXp0Y
  rmXpWLZNwml+aVYaeWK6Rv0hYu9Kl3U6JvcGnGa1s1pC3+PswuuDOwIDAQABo4GM
  MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
  AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUrzv9riM/nl6NLnWKi18pddbt
  CiMwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
  KoZIhvcNAQELBQADggEBAJRcm3oovuYXHj3WTizjHQx0TCn5lGWkrDf+s2+be4D2
  z48Lt4p+peGNv5aYulmuW21j5aMedlig9SKp38d1euMc4LWoJH5+9C23tdVbRPTB
  F8O6Z0LyqCUXJlwJQhFNWcOYbPytSgU+SgQCpzPZquHI3xkaf0O5fCU0v8iEq+0h
  upAX0XBTHPEvyyBEVrykgY01nP8tuoY5cZf1hG8Kdc/DE7TKHux3Evlncq+88YXG
  /VHhAOaDJ2xJK+xkQgoQrrz9afRJXacRp9o8lACeCzULa6VocGnQ3vIAcCb1+aQX
  kfhoEroqI2v2zB/N64JP4SRLJD+Gsf+AvFe1p91lFGI=
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDPjCCAiagAwIBAgIRAKqmRoNw5TqP3tvUVi317LAwDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI0MTAyOTEwNDYxNloXDTI1
  MTAyOTEwNDYxNlowJzEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMQ4wDAYDVQQDEwVh
  ZG1pbjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMVzwu9feehgClIL
  Afu/5+fnuvUOdmfrgH0f7AmYXBNAjxBg1xWHovVMF4cxoACDuJdWHf6+ZtKmijCK
  TWHyGFvpxAercxVR4fxKP+2TRJqxAmQDL825+x/fTe8EmHN+i19wFG41Y/ciERLD
  NMe80q2Cle3Pb7Wkne5JuM49S/6ixRDBH4dYmI/rnqt8ncfFVwlTTCBKLFLvuwvt
  aPEECsdmcvAn54S9hlxLLL/qVTEgtt14ycrNFEUsTV115KJriQcLHLdSfVNAggqG
  AB/mbP1j/LDA/6NZSBkAdLVsz6p7QZviSb7O3AmVW8HOl4DM+LM/Y69hHL+GT5Gb
  k43PP70CAwEAAaNyMHAwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUF
  BwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFK87/a4jP55e
  jS51iotfKXXW7QojMBAGA1UdEQQJMAeCBWFkbWluMA0GCSqGSIb3DQEBCwUAA4IB
  AQCBTP1oQblREQzYKd90A9VjaV75LPcgEHRtJmKeyqlpHorDdN3wpsoEw0kokVh8
  IoA1fPYMF+i+uSSRshgnqSy/S3c+7tx3OUVa1asE6Wbm6wtVyhG38VZVb3nCDKcv
  pNdFzlj6SGpURfjW27IBIYpNLDf6EhamDoG1O5tekTKGqBhd6GqBKvjxZ4dS3Uik
  jWXQGiSxQY8NzlmsYFBVrEwEBufQcz5nCQZiqsXxjHnR3rCT/VYw8hjSB1tKyvI6
  QpjGxbyc9WfkhMPIUVTK4VY3VhL39U6unPCHFqri+A436gKo1fkLzPnikPxifvgc
  VN7a3D6y+2aRMZYr1yBmmSvk
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAxXPC71956GAKUgsB+7/n5+e69Q52Z+uAfR/sCZhcE0CPEGDX
  FYei9UwXhzGgAIO4l1Yd/r5m0qaKMIpNYfIYW+nEB6tzFVHh/Eo/7ZNEmrECZAMv
  zbn7H99N7wSYc36LX3AUbjVj9yIREsM0x7zSrYKV7c9vtaSd7km4zj1L/qLFEMEf
  h1iYj+ueq3ydx8VXCVNMIEosUu+7C+1o8QQKx2Zy8CfnhL2GXEssv+pVMSC23XjJ
  ys0URSxNXXXkomuJBwsct1J9U0CCCoYAH+Zs/WP8sMD/o1lIGQB0tWzPqntBm+JJ
  vs7cCZVbwc6XgMz4sz9jr2Ecv4ZPkZuTjc8/vQIDAQABAoIBAFk/zRIT7u+ZUbDp
  5tibUsChHwGbquuoKGjmX/OqWZweJ0x46V+C8qa74TqrtK3m3C4Tr/UwrRt0SaxN
  J1MpcddB3+izl45Ad8xo52KEmZLuha0dP6NW+GrcrcZnJl22Clt2NtXl7iyLynnX
  oGjUMcpZ51kZ1V2ebgCCdDVMwafzsYTkjlEgVVjBFy4MwQ+4vY6TsxbYoxNa9Udd
  Xw0ybea01CL6qykMGgKw3sthfbCYq9/8zJj4xAPbsmpYkgEYH9KnfoVXH2lsbiCv
  SAsBaf+UB8ThdtWnh6EMUTqAvs/QAQ4kjqvoTAah3WIIOaeVFwYyUR+D4I68Y5RW
  jHiwQAECgYEA6erv9zHEDozAMa45Txichh9qXGCTVQGJ3eVDe8Zi0XYjebqqasID
  4YFcwYKs1Lc7xY53Dn9+9wEJux6n8VxAufpgJxeluh50ePryLHTvuVC9S1d16pwg
  Y2nglgis6TlnY5Pv5GQz9sYv+NPz9P8qmi/tRwvhsX+i5r0uD8HZr70CgYEA2BeQ
  2eK0vlaqCg4kJMIR1+ky9SMA9rAw5FjTF88+7gB2PSCn+oDUAo+9J9sbzmz2fYSv
  Q+Yw/bnxwl80BpmwvgA4ftvrvQoxkscYEWuswu1wgT1rySI72KzpoXLA+kmTsPiB
  z3bWqetyseQv5hi7Zk42jwHpLaUCD0jQ9Y6c0AECgYBidEAMCyY5+YPrZSk54WIA
  EbjyqLNaVAtzGcwNjLKK9u53jdmslXyMraYczKNx5K2DuTLjJ0aJMCaoW37UV7/m
  hztxOMLIU4kyYm0LySwdE56Y13cKCCyZqzab74rXnxGlF98gggxdEY2fbZaAx+Vm
  gEWeYaHc05v9AiMg/rZhAQKBgHQ+oR6E9UQbLNfB6bGYcK7cdRwn22HZQEPmgJAj
  Xa/8sZ6KjbKVUPebyV7CYL/4H9U/5mS5VQt41tQAEOWoEcr0JXAg8Dy+WhKiZZEh
  gktOHaJ4nx4Q+27A/eFq8OLzZ67g0DwBqtK3pPiLTzURguYzFuhxV7XFOUltm3Mt
  Z7ABAoGBAIlJ4StM7JdsZdqlxzW/RXSzApXxsUdk8UNDOphLATpq+neCEzNlR3i8
  0XuChzfYcoXCJto2wXffoBt07BCJZ2COZfBTjzltIRmpJcfQzwflb4LaTwjQaLYH
  02EIBhu5hVZsSVMyDLm3STxgm8mc7NDokmCSnicO3F/xjzBtDEuF
  -----END RSA PRIVATE KEY-----
api_connection_string: 10.45.154.74:8001
name: admin
