ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDTDCCAjSgAwIBAgIRAJ4xz0k49muEzNU4GLx6a04wDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI1MDExMzA1MjMyOVoXDTM1
  MDExMTA1MjMyOVowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
  hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqlKw+vkyQxzW8JeTjMsa+e6TLYj/1Npd
  1NpkDcBYGLDV5ipX0YguxyfsyHsLXgAH0LK6B11PueFKBAdIH2ngHPvPrHk4Je88
  rFpVrHKzIfXGEPP669nZDtcvm6P5o7tNLY+XtB2tNo7UjbDKIvUWFKoQhXogCJR0
  yUQU//5gyvoRuJy0cLT/S8sLu5CrzTreckkoN03QgNgjZupBMw/dpjeu/2eshAV1
  r3uKZP9lp665IqoRgCfxSA2rLFBipz1xnLuhkoR8XkJT6iapOZ5VWjtCCiDPLuMy
  h/wyH7IMiSik+8ByzSskvapckyGsu8orXQTlQKyOF0jFwDGs1krPrQIDAQABo4GM
  MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
  AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUBtCN49eXaU4LifKnzctgVKFF
  EAswKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
  KoZIhvcNAQELBQADggEBABB/E6/ZOiOClqeokNf4aalQYlw8JZd2fK1A+Xvgl9bU
  T9aCsyOnY9UY6StH+O1UHRsPpwk4pjFuNUkSIBazXxDF7BWr02ltIdOUdjlD3443
  Ln8jXjWmUnmr8pa1uDJzi5ixeyIEO2prco1lwauvZQ+YSqqTS9gVs/3kzBcbT7O1
  U/Nkw4YC6tnGWaNbtoHyGBHTArLShpCrcXbCj8qKf1tc8HvtOTOCCRZXqHysQmPA
  GqMapAX+Z3U3vcCqAjX5/ahKxh3JOKDMVPGHSt2EXSISF7Ijn7B9rf2bLp6LTmKA
  Tg0OekZvp2VxLdzVdk1XSoUeqCAfSXa6jVmf5YmP/mo=
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDPTCCAiWgAwIBAgIQLlQ42/Nhq6xDPyyS26RXvTANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjUwMTEzMDUyMzU1WhcNMjYw
  MTEzMDUyMzU1WjAnMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxDjAMBgNVBAMTBWFk
  bWluMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAy8ZGdStzJJmRR+yN
  KzC0PafbWzYMw+h/KhaBkfW5ukb9OfUsen1v28UICq9AjD5Kjagcl2P6gOEYhYUB
  Br2ya+0/SSTPwyz0X5K9POYUW4LUh3LTtUD7VEUbNAacgPvz3k/oObu6SflWcXH+
  9ZiLQRK18s9FuLjQMW+oWvEvLsImKv3YU4OjcSGatkqU77Fe/MVWmp9EB8qXjZm9
  qJaDm0CrvXcWUXsNhINpd/K1z3XtOYI7N486C0Wz26Y0KhCU0bYIw+tnGHSRgZwR
  JWjCSSK5gcWxSlR7I7Y+wW2wb4k4iaJ26zztkfNOoLpsGdWmTXQbZB+IgnCbXT88
  dIPCiwIDAQABo3IwcDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUH
  AwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUBtCN49eXaU4L
  ifKnzctgVKFFEAswEAYDVR0RBAkwB4IFYWRtaW4wDQYJKoZIhvcNAQELBQADggEB
  ABGmsd8XeVUSk7Z4Z3btBddJiM3MRkDbbUQ2oDTcuINZAKfFXbtHIK0DzYb6pMh+
  8kgz/vdaDulWX4JYLKRal1X4E5fCnhsIv+4YoiA/E1/qjX6KboJFZfsT8Xp2quDW
  WEYxkV0upnDn+BLoU4GDWqdMt0oqBP8B0IBW/K2VExg1175Hw9iTP9uxD0+qJbDS
  80IML43ad5YHMIT70fQho9cyoT22Dd+8sf4YDs86weYtNnyA6pMS0OM6s/mn6wGq
  es0L6Qu0rmBjRN3uEkO3xWhNCLQDTbpgCihK+y8kcCJqRuarY0Xg8odLU6WDynpQ
  Oyaui0vi1sJ3y5QZWs2adUs=
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAy8ZGdStzJJmRR+yNKzC0PafbWzYMw+h/KhaBkfW5ukb9OfUs
  en1v28UICq9AjD5Kjagcl2P6gOEYhYUBBr2ya+0/SSTPwyz0X5K9POYUW4LUh3LT
  tUD7VEUbNAacgPvz3k/oObu6SflWcXH+9ZiLQRK18s9FuLjQMW+oWvEvLsImKv3Y
  U4OjcSGatkqU77Fe/MVWmp9EB8qXjZm9qJaDm0CrvXcWUXsNhINpd/K1z3XtOYI7
  N486C0Wz26Y0KhCU0bYIw+tnGHSRgZwRJWjCSSK5gcWxSlR7I7Y+wW2wb4k4iaJ2
  6zztkfNOoLpsGdWmTXQbZB+IgnCbXT88dIPCiwIDAQABAoIBABuKA1GoepoyquC2
  hmmU3ncKrWmJR3ZegHkWq5InTF9xYp2nlchEFY709N5EywtpC7hTRPHs0BkE0sSQ
  sg/QKUHOwWPINs/gznHwKeUGDzBC4SghC52OV6kO4dtJHXONGWstD2xmA4olyVnx
  lwxn/kHgHnjfLEQHrhNQTMdlmwPNeYz/RYoYRcxuwkCrW8sjidlZy7gMItnV8Pyl
  Mycsmlma/0QmssfxYfX0orKVL3VxH/RuKH9ieN8SE5yrS0OJo32dSJAwHWrMDSA2
  22FjXAf0yU5Y4w28uZAvDekbbq8vnHvTpjRZ0OCmnwHQFuCU2ZmrJNX8TW8DwDhL
  4L1xGkECgYEA32RpSNcMlPByp8Ey5J4CkktBVY7zxfLJzTpw1zNw3JV3cl/ElhD1
  wcUV9En+asSEuTUbALfUGJX178TGGAjwJzomuKfmngjuOHQLUH0tW3M/vZI2PagI
  dbr+rJ928zFkuez3m31Q+nuDXHF/8crU49kwBXF5jTAWP7QyIiPagaECgYEA6YTM
  9wmbcxEvjPkI4G3pgNp0GuPYRGuEkUCC8OjxPCF3Ol+TuHOAh5GRryAGrLgWXKPG
  Ya057H2x9gNtC9UkRX7LvtNsAwtDLYuWBlY9Yknagfy8IA4sBBxsISS6ifMhAbxB
  W5aeE4/Y57zajizJ8/OB5WowpkciDAAbNO0XrKsCgYAuqhD8MD/mlNu+gzMYYpFy
  8dlx/+yYOwFAp6aOraYzzd0nvS2Zk21izsKpRxOoRejbr2Y2ni/l+t1m+pnOx38z
  EoioJhqchI0Oqd77L0rcQZTdCr/d3U33Gdq9QIpefsDlvcRzbJgP2uEz3Fm3roEO
  H35ShMO5ZIQhRoj6bLbmQQKBgExDJZkMFytWEnxsnDyHSLnfHgnmHSwDHRE+y0SY
  HqhvmXuD2T9k4TXlEXnq8KMZn5vzlIczxnX4etUIO2Wg3y6fATU54M2BsRe/vWgm
  Y/ekfOr0ug+R8UgKbDnKv+zrbP0fGQ0rPEbRNJpB7/J8qBu2i9Z7fpXfJzxaEIiR
  YajvAoGBANn1mzwcQTK5wdturWqzKf9drJyWed+e+nxCaekJVDMx3lFjUolENwmU
  d6XDID23QwmaQtVVm7cxLsgkiZ8MVyBjrh0uO07YQH3+AZNT4L7X1+bkHZrKO/GF
  4hQbmndsjgmxer4YYhcgjxcy4XuTiizeoJNNn31WLiB36NZNJNQ6
  -----END RSA PRIVATE KEY-----
api_connection_string: 10.45.154.74:8001
name: admin
