ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDSzCCAjOgAwIBAgIQNwoGmSuIf50PjS1e1ZnuVDANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQxMTE1MDUyODUwWhcNMzQx
  MTEzMDUyODUwWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
  SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDAIvI4fNu8bsIs+xvzEGk6325E9iIF0WRo
  oIKYvnivIYUr0rCwvj1nCCSqgts8Yx1TrS9fHOrSdRfQsaCvuR7TaU/tE7YtYOfw
  ABItyvbt3kyCze89mwgbrVcRRW1LeJNj2a+iM4+gjIakITqwo+C9Pgsqhwc+D4ms
  qkbMzRlC3VMn5+ZiAlmwopzALVkfPk4Jbom2XxEvmlJGkBvX0hMVz9dozPmgTSB0
  hX/umtYsD/IIzDtjlXEJmjPSMNGvLAU7grdFu65NnQgdrVN/bud2LixYmnt9tzac
  UNnT2K+MpqlnMNrsuPiX3oCrOoXo2TQTWVPZZ9+A2YTO9eg6pFuZAgMBAAGjgYww
  gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
  AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRFX4yAuvWvkZ7101co/cz+eMPu
  SDAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
  hkiG9w0BAQsFAAOCAQEAaxxNjlPZQ8ys5ENaNl2K41lOauIUaE8v6ceEqL36klBw
  x6kybD/FeCrFVTUCLkuXNEYon6rEF08/gAIdX00DVAe6z2/vHimIghFS49BU/oQF
  rQvvxKCcQrWvpIxdto3n3gG5fI8fRw/4YREK2Osr4lelSeifyyqF/F+5NMPdP3v5
  GZeC7di0i+asr9haybepKlGYy0XUjQE/160iSpPQ1kMIUE/H7MuNNwgt2p9g+4PA
  rIg1dWpDCcDAlfgKpW1hpUZ4/YaOODLK65FnFotZ41onTm/aof6Z21eFXsY4NYBy
  v+SAoeAd5YNrvebZAC970ZPFVHI4jAPD8SqKtYL0pA==
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDPTCCAiWgAwIBAgIQKAOtkkuRXeOCA8D08vMVJTANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQxMTE1MDU0MDUyWhcNMjUx
  MTE1MDU0MDUyWjAnMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxDjAMBgNVBAMTBWFk
  bWluMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1UJwiFzNY6ge2hO9
  cch6RTiPx6UBG0Pq/VjDku0vSw0p+wX5rMQqi0bLrZxXyC6OFGh9WUS4/hX216Kt
  TfQM4gcfiUCfk9FSG6OLW1PC23npkpfk479qBvnHW9HKvA3nbQa1gjVH9uEYDy8b
  RD8N9YH7i0S9zXykHjjgxOe1i6+xVy+ft3RtMMLY7hIk4Fj3ykwK8tsFt5dnS9og
  sn+7yzRdPy0CP2Y2/DzhlTmYBrzZB54l10xIb55Vasabqq8tcgBDXNPrNHlFTLUT
  vfedMl71qO8r9YbFZHGRGty3W1gU4XzwWSEN32zc1ogocAdNypcTcPHfA74ayCDC
  f33IiwIDAQABo3IwcDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUH
  AwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAURV+MgLr1r5Ge
  9dNXKP3M/njD7kgwEAYDVR0RBAkwB4IFYWRtaW4wDQYJKoZIhvcNAQELBQADggEB
  AKoptJl8wh9S7UpwwrDDKseSLfNO65PYrqvgmsFxrj9W8uV8wxI5UV/IPp9PoN4k
  6EAQyw3+xvCDwz5rP8mzRORRn+hEKDxN2owTs5O4XRmUzpxe1dUBot+puOdc+QNY
  yxkl4JNskGhldZfn2JYgqkQLlT04e+fdrucA0NrbLEzEmHirRshqQmecoCNoBEum
  CTpOHAH5VkhnVQK12AGAY+hwLbmHab0O38FR//5X+0/LYaXTOmEjfwh32cugo0Q6
  EazrDHxNW8sd7sN5P1U/AIg74aMv9IzOLtdLJEvOoJVheRTxUuU+tGLZkvh5AmRs
  iKAAk4WbnoUY+CrPpbGOQqI=
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEA1UJwiFzNY6ge2hO9cch6RTiPx6UBG0Pq/VjDku0vSw0p+wX5
  rMQqi0bLrZxXyC6OFGh9WUS4/hX216KtTfQM4gcfiUCfk9FSG6OLW1PC23npkpfk
  479qBvnHW9HKvA3nbQa1gjVH9uEYDy8bRD8N9YH7i0S9zXykHjjgxOe1i6+xVy+f
  t3RtMMLY7hIk4Fj3ykwK8tsFt5dnS9ogsn+7yzRdPy0CP2Y2/DzhlTmYBrzZB54l
  10xIb55Vasabqq8tcgBDXNPrNHlFTLUTvfedMl71qO8r9YbFZHGRGty3W1gU4Xzw
  WSEN32zc1ogocAdNypcTcPHfA74ayCDCf33IiwIDAQABAoIBAHxr0vP8EOi/waBC
  PBkSeiPAqEI2hrq9mXBORWyHbTxAZenKxqyBlsDDgTm9KYnlf4dwnxFiAvxbHDUa
  +Dmu1YVZ2pBdX70CNwFhHYEfEWSzcA7TB/vIRbfkKufrMnkdM5RsgaGCLIZhNYRG
  W4Yps581QukyJfqpaacoUBsRhN4FhgpEdMwdZfRT+GBIC1eXI9FELwkfdfb/Ew2R
  aTVxL9wbSdFyv+gRMomAqI28Kx4QJ5RwmKJwwB8nm2N7vhyDlC0IMRQfQ4rkP7Xc
  x8SKwZVT2ETlAX6XPhuqB5510l12LYFFSiyXsLKv2p0NIR+rQqujezZdmDgJ8BUU
  fPWItMECgYEA2g3qbVFvNU/iwSYbltaar6fPQb2H0Jdzz2kZZ8RR4u6/RYFxtL1e
  xNk02VwdfgWu1mCSW/H4pNrFLtFQD1u7WFeUOeqdxja8J5lPkec85s2Ai3s+rcFq
  PEJS9iDOO1rwiYBZ5KH+2o3pB3CV/R38oajqXtmGgKpOT05dUVwBlukCgYEA+l7r
  YSeGh7N+0cYV6v9cxqVJOv4BZcUvA9zUw0aKXe1xOS+MGwG9kPh0dG3j758fDxMv
  zU2u5EIfmDzOdaZhmnLZvqUDSh8+Q3mE9shidGer12nUw+rVZoocAy21IyWZhlkq
  ChGx0Y07pmQ0+S5XCUiL2lBIluZlzf/n53GYI1MCgYA8gUoARW1vRJht8e4L38aS
  YSUAX9/0wGGxNr+G7JGwP4ExfyaW+Uj3pDGm8ol4c4k9ERTrkGvnCpFWWVw2tsR4
  UezeWTyoSH3TGxZaLOjYPkOh8HPG8PlSeTDd/OJc0/IUpVnMOCsoZ+I2X0YvMwfr
  r5xA72kEAL20AdGhBr+mKQKBgQDtUxA3FapV83UhD20zRkABJCfYPXHBsDmypZ8g
  QzthcXNDy6g46VtxkbGBs7C+MMzWE0/agepn/63HNsxVhRM7veZc6jnGBvuUJho9
  exCoWqTvGihOVclW209WS/tJh5iRWu+Yf9FYW1HRlWcJVD24VQYMONG2CEs0C4Ed
  R/X4dQKBgEdcwiUefLyqZObAWU4mUtQMtU0LkRLPtwAQVm0sCTsWmQseV9wNnRHi
  n/m2yupK3pX9kvOkwM2OU64fkqW3+SnhOESBjY78nLha7qyyaBtXmskQnrtTl/7v
  h2jlOJpmi2SCSHQwUsbGvPzisiQoN13vYChT2O9x9rP9Gp1Rr+PR
  -----END RSA PRIVATE KEY-----
api_connection_string: 10.45.154.74:8001
name: admin
