ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDTDCCAjSgAwIBAgIRAPAN7PbVJNhDtBlT92QENYAwDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI0MTExOTA3MjAyNloXDTM0
  MTExNzA3MjAyNlowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
  hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsXKAif+h18yypSX0TkFne9txx/Ya02/j
  hiNWFTFcKWb7l0HxPC6KCDsyr2TKh3Z/2nxH+wR+g3cEItxQlhttrWxhBGY/+LF6
  Y7PnowmkqjfkRta8KDVjyVomuSRH6mswQRw0wFGz/NM54Eb9PbC4X2p6xasqyiSe
  8RNudF7d91SDBtesS5Oc/kwDVuB9WfXKvV9pYeUAv3f8ATNqrjgiJfAvm8Y5zqtC
  kc34uAy0jAsjdMiDMDk75sZqLOu9eMHDqlldg89Ep0onRwgwyWpItne8aNkk0ZMy
  oUwgMMFq9tk5jXUSdcJUWHkRVOb0qyrxTbbmOvkMTtIbxVdB3DWDBQIDAQABo4GM
  MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
  AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU1TZht4cQPi+wqEfNaUWEm3av
  kIgwKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
  KoZIhvcNAQELBQADggEBAHC75ZFYrvxcmBYH9PeaQkoESNLzrMLK/mvVPPBWCOlL
  nbQ6u+38cR0SCI36CSjz4WivhkknOjfptu7PIxv6DNJlW4q7/NF8+UHFffntTX8T
  Ixda9yCZR/lYZISE6Gc9u133TGjzxdV/90rlhhzDkCfIfcC3DJbCJpg/EiAVUlwb
  vKArvasVFv9ooLOlblj2uJDcyATp+Kyc2Ir7lS4WyE9A9dNzrJ2vdc8rmgkSxfke
  bndPnx3527l1/1lHdb8IaWROn3SSeQrKSet9uL4LX/QxKtXjrHgNUYAxs71elUuI
  ybET0RQDw/z0qVNrcN6wqiXpI/GazbpNcPRkfbbYDdc=
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDPjCCAiagAwIBAgIRANSctn6pNf6ie7y2QV/atS0wDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI0MTExOTA3MjA1MFoXDTI1
  MTExOTA3MjA1MFowJzEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMQ4wDAYDVQQDEwVh
  ZG1pbjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL32m/JVAPN9Bbu8
  2n31GMIPlRvmlab+OKe5GdU8GZ488JB57f06euyl187pnIcJl/BtDUX5RAdZ5qUi
  3M2EqDefMS8oR5eqrkRpZ2p0VXS96IDIcfzE1y2frbMeXg9UnUIhVO4O3HwiaKGC
  1JrXvXxsAv08UTWkzq7GJ35vjvlYb+vJifhu1mDZjzxPcIxDtbD1mjH9XtVEB/Ee
  rGt4I+NXz+o7Qwu1qFeVPhUGTEBdCQ16gYU3S2CPYwaLiedYmwaJw3m4QtKamRsI
  ax3JnPbiWC3BiPoV65QftXOUZTnx7bsOIDMurCdQrGUjZJvUojDfX2/LAYKK4xtQ
  ssxl4GECAwEAAaNyMHAwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUF
  BwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFNU2YbeHED4v
  sKhHzWlFhJt2r5CIMBAGA1UdEQQJMAeCBWFkbWluMA0GCSqGSIb3DQEBCwUAA4IB
  AQBDZu+bEBsUGC6Mv/33T7QejVjdI5pPKfZSvZJQHtZF8JY8zvrD7Nq6aFfaPoh6
  mublyUrrCCSzPCIAVmd3NRTWRGJRxurwWQiiVqbEP7ARMnl1FQsAYLYK7KmWDqHd
  rlTHhNV9faPKdRNQYBkdFDnwvgZM+WupSS9VR76KuMbqvWd5tXuX+LxgGRb2V/mr
  VN3BTExnhpolYc3sLrZqHaIgU7otCqGEhP7c3B6AdqU17QqCw6US8duQK1+oVtCO
  /Iz3be9hACqXQcZcmSuWUjquZlOHU9fOKlAoCMWz1rLVE1zt/30j0hrMDGPj+phD
  w4q3ufjxkcl+Qqz0HvW/HEJm
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEogIBAAKCAQEAvfab8lUA830Fu7zaffUYwg+VG+aVpv44p7kZ1TwZnjzwkHnt
  /Tp67KXXzumchwmX8G0NRflEB1nmpSLczYSoN58xLyhHl6quRGlnanRVdL3ogMhx
  /MTXLZ+tsx5eD1SdQiFU7g7cfCJooYLUmte9fGwC/TxRNaTOrsYnfm+O+Vhv68mJ
  +G7WYNmPPE9wjEO1sPWaMf1e1UQH8R6sa3gj41fP6jtDC7WoV5U+FQZMQF0JDXqB
  hTdLYI9jBouJ51ibBonDebhC0pqZGwhrHcmc9uJYLcGI+hXrlB+1c5RlOfHtuw4g
  My6sJ1CsZSNkm9SiMN9fb8sBgorjG1CyzGXgYQIDAQABAoIBADICSxmnwSFYp3q+
  A/Mm5AaqnYGD2Z/lyzp0Y1Wchc3/kwEl6D5C9/t2yXKCU5/FKce0ncrvDTa2Nx8A
  J4q/Qp2p/gPBId/OoiQGb6A50glyuVO18TQvCcrL/6lo9DArAV9YcQhexzKyyELE
  s320EAFCWiMajvKFWZfvOJRzf/sqFQViIqhrNebsjpt86PBAyyAvypecMwKXCLnN
  7hwnximX21O8uBmmMWlK8lrFihR998sSd0TNLCClfpJBvnQ7RKUrStcDq6/SDbM1
  OUNPh+dU1QvdUv5V9sNkbBh5im5Lc7LuwYabs663HN4hbCLMRiLiiSkIlbTfSOQB
  4x1/6QECgYEA+Ye4LJPNBeELbjADVULx9J6Nzqz+V8yjV8A0XGIAkzQ29RPN8waM
  VWQZWkME1Hf/Lori01Ix9FsmRWMFNWcH3Q9IL0EUQh9F0TtxfpdSBgT/7kC2Btag
  BJYWwd3zWC+bA9/mVPI96TwLD8mCNtDRqj/LRBI+qWUovO3VqRInchECgYEAwuOC
  U223A2ByGI9eVg6rMSiPT9a96LzVo+/x3dATTNMQ0O6NiwpOTKcQHKdv5P1paHrB
  EswGFTegxRbbFspU2qBZ1ser3w4z8412XMRM1pJ+rpX8I2cm8qZTJiszl6jPorPA
  +YNd58kHYyqasNL5OI8QRyxwL38TsHambCg1OVECgYBR3kOA7KUxrppPdpVBXguA
  VJz2GDAConNdEQSc4tKJeXImim7hs15LjeH7iU2GYDBrFspAxxD4uQcfcNN+p+Ue
  lCr8xf9dimEfur8L553Tt8Q4aSbPq48osg2ZYba7UjMr3EP3ztqdMUP31AdS8MQ5
  dWC9XrcMYNIy2l1lcT1b4QKBgAJq6hn42XVcQ+4UETqGEg+ZDjYSVubFOO1As8Jp
  q2OflqzQ2MapyRDgXa3NUfEIR795Dl4aU9T9jKwFPZCJ0AWqSZMFhRdOSMyzq405
  Di73QEUQLUGPLQeDkrJ9hLVT7cd57WHrBEY00zeitqqM43SVKcGIRpgAPpFI14Wt
  9gMRAoGANJq7g8vDACvUdMCfJBaib6tJB1JK6yeBn76n0YzYttZpd89QpZUrE2df
  cDQGIn0/4H2OvZna0Bep1CN/AUnreq4JbXftMv1dZWhGH252XkZjRCpj1rZfPXjK
  GAZBaNCfsFGIxFNAXu/RLR1+vfWvm5Oa+eNp/qo+vv+P5z8yctU=
  -----END RSA PRIVATE KEY-----
api_connection_string: 10.45.154.74:8001
name: admin
